export const DATABASE_ID='gitconnect'
export const PROFILES_COLLECTION_ID='profiles'
export const WORK_COLLECTION_ID='work'
export const SCHOOL_COLLECTION_ID='school'
export const SOCIALS_COLLECTION_ID='socials'
export const STORAGE_AVATARS='avatars'
export const STORAGE_POSTS='posts'
