name: Deploy to Appwrite Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./appwrite

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Appwrite CLI
      - name: Install Appwrite CLI
        run: curl -sL https://appwrite.io/cli/install.sh | bash

      # Appwrite client
      - name: Setup Appwrite
        run: appwrite client --endpoint ${{ secrets.APPWRITE_ENDPOINT }} --project-id ${{ secrets.APPWRITE_PROJECT_ID }} --key ${{ secrets.APPWRITE_API_KEY }}

      # Appwrite login
      # Use appwrite login since client api key does not set session required for push
      - name: Login to Appwrite
        run: appwrite login --endpoint ${{ secrets.APPWRITE_ENDPOINT }} --email ${{ secrets.APPWRITE_EMAIL }} --password ${{ secrets.APPWRITE_PASSWORD }}

      # Push changes to Appwrite Cloud
      - name: Push changes to Appwrite Cloud
        run: appwrite push all --all --force --verbose
