name: Deploy to Appwrite Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./appwrite

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Appwrite CLI
      - name: Install Appwrite CLI
        run: curl -sL https://appwrite.io/cli/install.sh | bash

      # Login to Appwrite
      - name: Login to Appwrite
        run: appwrite login --endpoint ${{ secrets.APPWRITE_ENDPOINT }} --key ${{ secrets.APPWRITE_API_KEY }}

      # Set project ID
      - name: Set Appwrite Project
        run: appwrite client --projectId ${{ secrets.APPWRITE_PROJECT_ID }}

      # Push changes to Appwrite Cloud
      - name: Push changes to Appwrite Cloud
        run: appwrite push --all --force
